cargo-features = ["strip"] # nightly

[package]
name = "uad_gui"
description = "A cross-platform GUI debloater for android devices"
version = "0.2.2"
authors = ["w1nst0n"]
license = "GPL-3.0"
homepage = "https://gitlab.com/W1nst0n/universal-android-debloater-rs"
repository = "https://gitlab.com/W1nst0n/universal-android-debloater-rs"
readme = "README.md"
keywords = ["debloater", "android", "adb", "privacy", "bloatware"]
categories = ["gui"]
edition = "2021"

[features]
default = ["wgpu"]
wgpu = [] # iced/wgpu is default
glow = ["iced/glow"] # OpenGL support

[dependencies]
iced = { git = "https://github.com/hecrj/iced.git" }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
static_init = "^1.0"
fern = { version = "^0.6", features = ["colored"] }
log = "^0.4"
chrono = "^0.4"
regex = "^1.5"

[profile.release]
opt-level = "s"
lto = true
strip = "symbols"